server:
  port: 9101
eureka:
  instance:
    hostname: server1 #在host进行配置
  client:
    serviceUrl:
      defaultZone: http://admin:123@server1:9101/eureka/,http://admin:456@server2:9102/eureka/,http://admin:789@server3:9103/eureka/
spring:
  application:
    name: server-cluster
  security:
    user:
      name: admin
      password: 123