eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123@server1:9100/eureka/
server:
  port: 9301
spring:
  application:
    name: service-client-personal
  rabbitmq: #Config刷新总线BUS需要连接RabbitMQ
    host: 192.168.31.55
    port: 5672
    username: demo
    password: 123456
  boot:
    admin:
      client:
        url: http://localhost:9400
feign:
  hystrix:
    enabled: true #使熔断器接口方法实现方式起作用(OpenFeign自带Hystrix,但是默认没有打开)
management:
  endpoints:
    web:
      exposure:
        include: "*" #2.0版本server或client必须加上此配置,不然无法通过这个/actuator/bus-refresh刷新,还可以开启hystrix.stream
turbine:
  appConfig: service-client-personal,service-client-order,service-client-cosumer  #配置需要监控的服务名(spring.application.name)
  clusterNameExpression: new String("default") #默认为服务名的集群,此时用默认即可
#turbine集群配置
#turbine:
#  app-config: eureka-client-consumer1,eureka-client-consumer2  #需要监控的服务名(Eureka的name)
#  aggregator:
#    cluster-config: kanjia,gateway #需要监控的服务集群名
#  cluster-name-expression: metadata['cluster']
#  combine-host: true
#  instanceUrlSuffix:
#    kanjia: actuator/hystrix.stream    #key为clusterConfig的集群名字，默认为default
#    gateway: actuator/hystrix.stream    #value为集群的hystrix监控url后缀，springboot2.0默认为actuator/hystrix.stream