spring:
  mail:
    host: smtp.qq.com
    username: 1198127035@qq.com
    password: rwzochieatynfihe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true