eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123@server1:9100/eureka/ #仅需要向集群中的某个EurekaServer注册即可
server:
  port: 9200
spring:
  application:
    name: config-server-single
  cloud:
    config:
      label: master #表示是哪一个分支
      server:
        git:
          uri: https://github.com/1198127035/SpringCloudConfigRepository
          search-paths: respo #表示读取SpringCloudConfigRepository项目,下面的respo文件下面的配置文件(可以设置其他的文件)
encrypt:
  key: no # 对称加密，配置为no就需要启动时传入秘钥