eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:123@server1:9100/eureka/
server:
  port: 9303
spring:
  application:
    name: service-client-consumer
  rabbitmq: #Config刷新总线BUS需要连接RabbitMQ
    host: 39.108.82.13
    port: 5672
    username: guest
    password: guest
  boot:
    admin:
      client:
        url: http://localhost:9400
feign:
  hystrix:
    enabled: true #使熔断器接口方法实现方式起作用
management:
  endpoints:
    web:
      exposure:
        include: "*" #2.0版本server或client必须加上此配置,不然无法通过这个bus-refresh刷新