spring:
  datasource:
    url: jdbc:mysql://server1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: server1 #连接的主机
    password: mypassword #密码
    port: 6379 #端口号
    timeout: 5000 #连接超时时间
    database: 0 #使用第0号数据库
    lettuce:  #和jedis类似
      pool:
        min-idle: 0 #连接池中的最小空闲连接 默认 0
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 #连接池中的最大空闲连接 默认 8
        max-active: 8 #连接池最大连接数（使用负值表示没有限制） 默认 8
mybatis:  #配置为多数据源的时候这些配置需要在每个数据源里面单独配置
  type-aliases-package: com.main.entity.*
  mapper-locations: classpath*:mapper/**Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
server:
  port: 9003