spring:
  datasource:
    druid:
      url: jdbc:mysql://server1:3306/test?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.main.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #YML配置打印SQL
